### ISSUE TITLE
Two tests are failing on Java 8

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/boqa#1]
> Failed tests: 
>   BOQATest.testBOQAOnInternalOntology:399->checkInternalSimValues:164 expected:<0.9163> but was:<0.2231435513142097>
>   BOQATest.testVsOldItemMax:478->checkHPOSimValues:429 expected:<0.162568779> but was:<0.423493625660376>

May be badly designed tests, or an actual problem in Ontologizer or in BOQA.

**Comment by antonkatz** [comment]
Denys, I'm working on this so no need to worry.
